service: 'srikant'

provider:
    name: aws
    runtime: nodejs18.x
    stage: development
    region: ap-south-1


functions:
  app:
    handler: index.handler
    name: srikant
    events:
        - http: 
            path: /
            method: ANY
            cors: true
        - http:
            path: /{proxy+}
            method: ANY
            cors: true

plugins: 
  - serverless-offline